name: 2022-08-01-uproot-awkward-columnar-hats
channels:
   - conda-forge
dependencies:
   - uproot==4.3.3
   - awkward==1.8.0
   - pyarrow==8.0.0
   - numpy==1.21.*
   - scipy==1.8.1
   - matplotlib==3.5.2
   - pandas==1.4.3
   - hist==2.6.1
   - vector=0.8.5
   - numba
   - xrootd==5.4.3
   - root==6.26.4
   - particle==0.20.1
   - pip==22.2.1
   # - pip:
   #     - particle==0.20.1
   #     - vector==0.8.5
