name: 2022-08-01-uproot-awkward-columnar-hats
channels:
   - conda-forge
dependencies:
   - awkward
   - pyarrow
   - numpy
   - scipy
   - matplotlib
   - pandas
   - hist
   - numba
   - xrootd
   - root
   - pip
   - pip:
       - uproot
       - particle
       - vector
